### ISSUE TITLE
lightdm not found

### ISSUE THREAD

**Issue by SergioRibera** [hertg/lightdm-neon#6]
When i use ligthdm webkit 2 greeter, lightdm object not found. This makes it load the mock by default, maybe I'm doing something wrong or the theme is not compatible with webkit2, if I can help in any way, I am at disposal

***Logs Details***:

<details>
<summary>cat /var/log/lightdm/seat0-greeter.log</summary>
<br>
<blockquote>
file:///usr/share/lightdm-webkit/themes/neon/bundle.js:1:769846: CONSOLE DEBUG lightdm not found, api will be mocked
file:///usr/share/lightdm-webkit/themes/neon/bundle.js:1:771517: CONSOLE DEBUG the web greeter is ready, initializing...
file:///usr/share/lightdm-webkit/themes/neon/bundle.js:1:771576: CONSOLE DEBUG lightdm [object Object]
file:///usr/share/lightdm-webkit/themes/neon/bundle.js:1:771616: CONSOLE DEBUG greeter_config [object Object]
file:///usr/share/lightdm-webkit/themes/neon/bundle.js:1:770206: CONSOLE DEBUG connecting to lightdm signals using theme [object Object]
file:///usr/share/lightdm-webkit/themes/neon/bundle.js:1:771892: CONSOLE DEBUG default_session is 'awesome'
</blockquote>
</details>

<details>
<summary>cat /var/log/lightdm/lightdm.log</summary>
<br>
<blockquote>
[+0.00s] DEBUG: Logging to /var/log/lightdm/lightdm.log<br>
[+0.00s] DEBUG: Starting Light Display Manager 1.30.0, UID=0 PID=689<br>
[+0.00s] DEBUG: Loading configuration dirs from /usr/share/lightdm/lightdm.conf.d<br>
[+0.00s] DEBUG: Loading configuration dirs from /usr/local/share/lightdm/lightdm.conf.d<br>
[+0.00s] DEBUG: Loading configuration dirs from /etc/xdg/lightdm/lightdm.conf.d<br>
[+0.00s] DEBUG: Loading configuration from /etc/lightdm/lightdm.conf<br>
[+0.00s] DEBUG:   [LightDM] contains unknown option display-setup-script<br>
[+0.00s] DEBUG: Registered seat module local<br>
[+0.00s] DEBUG: Registered seat module xremote<br>
[+0.00s] DEBUG: Using D-Bus name org.freedesktop.DisplayManager<br>
[+0.00s] DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’<br>
[+0.00s] DEBUG: Monitoring logind for seats<br>
[+0.00s] DEBUG: New seat added from logind: seat0<br>
[+0.00s] DEBUG: Seat seat0: Loading properties from config section Seat:*<br>
[+0.00s] DEBUG: Seat seat0 has property CanMultiSession=no<br>
[+0.00s] DEBUG: Seat seat0: Starting<br>
[+0.00s] DEBUG: Seat seat0: Creating greeter session<br>
[+0.01s] DEBUG: Seat seat0: Creating display server of type x<br>
[+0.01s] DEBUG: Seat seat0: Plymouth is running on VT 1, but this is less than the configured minimum of 7 so not replacing it<br>
[+0.01s] DEBUG: Quitting Plymouth<br>
[+0.08s] DEBUG: Using VT 7<br>
[+0.08s] DEBUG: Seat seat0: Starting local X display on VT 7<br>
[+0.08s] DEBUG: XServer 0: Logging to /var/log/lightdm/x-0.log<br>
[+0.08s] DEBUG: XServer 0: Writing X server authority to /run/lightdm/root/:0<br>
[+0.08s] DEBUG: XServer 0: Launching X Server<br>
[+0.08s] DEBUG: Launching process 699: /usr/bin/X :0 -seat seat0 -auth /run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch<br>
[+0.08s] DEBUG: XServer 0: Waiting for ready signal from X server :0<br>
[+0.08s] DEBUG: Acquired bus name org.freedesktop.DisplayManager<br>
[+0.08s] DEBUG: Registering seat with bus path /org/freedesktop/DisplayManager/Seat0<br>
[+0.24s] DEBUG: Loading users from org.freedesktop.Accounts<br>
[+0.24s] DEBUG: User /org/freedesktop/Accounts/User1000 added<br>
[+1.74s] DEBUG: Got signal 10 from process 699<br>
[+1.74s] DEBUG: XServer 0: Got signal from X server :0<br>
[+1.74s] DEBUG: XServer 0: Connecting to XServer :0<br>
[+1.74s] DEBUG: Seat seat0: Display server ready, starting session authentication<br>
[+1.74s] DEBUG: Session pid=804: Started with service 'lightdm-greeter', username 'lightdm'<br>
[+1.78s] DEBUG: Session pid=804: Authentication complete with return value 0: Success<br>
[+1.78s] DEBUG: Seat seat0: Session authenticated, running command<br>
[+1.78s] DEBUG: Launching process 807: /usr/bin/numlockx on<br>
[+1.79s] DEBUG: Process 807 exited with return value 0<br>
[+1.79s] DEBUG: Seat seat0: Exit status of /usr/bin/numlockx on: 0<br>
[+1.79s] DEBUG: Session pid=804: Running command /usr/bin/lightdm-webkit2-greeter<br>
[+1.79s] DEBUG: Creating shared data directory /var/lib/lightdm-data/lightdm<br>
[+1.79s] DEBUG: Session pid=804: Logging to /var/log/lightdm/seat0-greeter.log<br>
[+1.97s] DEBUG: Activating VT 7<br>
[+1.97s] DEBUG: Activating login1 session c1<br>
[+1.98s] DEBUG: Seat seat0 changes active session to c1<br>
[+1.98s] DEBUG: Session c1 is already active<br>
[+2.41s] DEBUG: Greeter connected version=1.30.0 api=1 resettable=false<br>
[+2.66s] DEBUG: Greeter requests data directory for user s4rch<br>
[+2.66s] DEBUG: Creating shared data directory /var/lib/lightdm-data/s4rch<br>
[+20.95s] DEBUG: Greeter start authentication for s4rch<br>
[+20.95s] DEBUG: Session pid=973: Started with service 'lightdm', username 's4rch'<br>
[+20.97s] DEBUG: Session pid=973: Got 1 message(s) from PAM<br>
[+20.97s] DEBUG: Prompt greeter with 1 message(s)<br>
[+23.55s] DEBUG: Continue authentication<br>
[+23.57s] DEBUG: Session pid=973: Authentication complete with return value 0: Success<br>
[+23.57s] DEBUG: Authenticate result for user s4rch: Success<br>
[+23.57s] DEBUG: User s4rch authorized<br>
[+24.58s] DEBUG: Greeter requests session bspwm<br>
[+24.58s] DEBUG: Seat seat0: Stopping greeter; display server will be re-used for user session<br>
[+24.58s] DEBUG: Terminating login1 session c1<br>
[+24.58s] DEBUG: Session pid=804: Sending SIGTERM<br>
[+24.61s] DEBUG: Session pid=804: Exited with return value 0<br>
[+24.61s] DEBUG: Seat seat0: Session stopped<br>
[+24.61s] DEBUG: Seat seat0: Greeter stopped, running session<br>
[+24.61s] DEBUG: Registering session with bus path /org/freedesktop/DisplayManager/Session0<br>
[+24.62s] DEBUG: Session pid=973: Running command /etc/lightdm/Xsession bspwm<br>
[+24.62s] DEBUG: Creating shared data directory /var/lib/lightdm-data/s4rch<br>
[+24.62s] DEBUG: Session pid=973: Logging to .xsession-errors<br>
[+25.22s] DEBUG: Activating VT 7<br>
[+25.22s] DEBUG: Activating login1 session 2<br>
[+25.23s] DEBUG: Seat seat0 changes active session to <br>
[+25.23s] DEBUG: Seat seat0 changes active session to 2<br>
[+25.23s] DEBUG: Session 2 is already active<br>
</blockquote>
</details>

<details>
<summary>cat /var/log/lightdm/x-0.log</summary>
<br>
<blockquote>
X.Org X Server 1.21.1.3
X Protocol Version 11, Revision 0
Current Operating System: Linux archlinux 5.15.52-1-lts #1 SMP Sat, 02 Jul 2022 20:04:03 +0000 x86_64
Kernel command line: BOOT_IMAGE=/vmlinuz-linux-lts root=UUID=db87bcaa-ef02-4b9c-9df6-6b33fd1584e8 rw rootflags=subvol=@ loglevel=3 fbcon=nodefer quiet splash vt.global_cursor_default=0
 
Current version of pixman: 0.40.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Mon Jul 25 01:29:43 2022
(==) Using config directory: "/etc/X11/xorg.conf.d"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
MESA-LOADER: failed to open evdi: /usr/lib/dri/evdi_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/dri, suffix _dri)
failed to load driver: evdi
kmsro: driver missing
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to open evdi: /usr/lib/dri/evdi_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/dri, suffix _dri)
failed to load driver: evdi
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
kmsro: driver missing
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to open evdi: /usr/lib/dri/evdi_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/dri, suffix _dri)
failed to load driver: evdi
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
kmsro: driver missing
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to open evdi: /usr/lib/dri/evdi_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/dri, suffix _dri)
failed to load driver: evdi
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
kmsro: driver missing
(II) AIGLX: Suspending AIGLX clients for VT switch
(II) Server terminated successfully (0). Closing log file.
</blockquote>
</details>

<details>
<summary>cat /var/log/lightdm/x-1.log</summary>
<br>
<blockquote>

X.Org X Server 1.21.1.3
X Protocol Version 11, Revision 0
Current Operating System: Linux archlinux 5.15.32-1-lts #1 SMP Mon, 28 Mar 2022 08:54:31 +0000 x86_64
Kernel command line: BOOT_IMAGE=/vmlinuz-linux-lts root=UUID=db87bcaa-ef02-4b9c-9df6-6b33fd1584e8 rw rootflags=subvol=@ loglevel=3 fbcon=nodefer quiet splash vt.global_cursor_default=0
 
Current version of pixman: 0.40.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.1.log", Time: Wed Apr  6 12:22:00 2022
(==) Using config directory: "/etc/X11/xorg.conf.d"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
The XKEYBOARD keymap compiler (xkbcomp) reports:
Warning:          Could not resolve keysym XF86EmojiPicker
Errors from xkbcomp are not fatal to the X server
(II) AIGLX: Suspending AIGLX clients for VT switch
(II) Server terminated successfully (0). Closing log file.
</blockquote>
</details>

***Configuration details***:

<details>
<summary>cat /etc/lightdm/lightdm.conf</summary>
<br>
<blockquote>
[LightDM]<br>
run-directory=/run/lightdm<br>
display-setup-script = /etc/lightdm/screens.sh<br>
[Seat:*]<br>
greeter-session=lightdm-webkit2-greeter<br>
session-wrapper=/etc/lightdm/Xsession<br>
greeter-setup-script=/usr/bin/numlockx on<br>
</blockquote>
</details>

<details>
<summary>cat /etc/lightdm/lightdm-webkit2-greeter.conf</summary>
<br>
<blockquote>
[greeter]<br>
debug_mode          = true<br>
detect_theme_errors = true<br>
screensaver_timeout = 300<br>
secure_mode         = true<br>
time_format         = LT<br>
time_language       = auto<br>
webkit_theme        = neon<br>
[branding]<br>
background_images = /usr/share/backgrounds<br>
logo              = /usr/share/pixmaps/archlinux-logo.svg<br>
user_image        = /usr/share/pixmaps/archlinux-user.svg<br>
</blockquote>
</details>

<details>
<summary>cat /etc/lightdm/screens.sh</summary>
<br>
<blockquote>
xrandr --output eDP --primary --mode 1600x900 --pos 1080x1020 --rotate normal --output HDMI-A-0 --mode 1920x1080 --pos 0x0 --rotate right --output DVI-I-4-4 --off --output DVI-I-3-3 --off --output DVI-I-2-2 --off --output DVI-I-1-1 --off
</blockquote>
</details>

**Comment by hertg** [comment]
Thanks for the report. As pointed out in the README, this theme is not compatible with the unmaintained `lightdm-webkit2-greeter`. It's developed for the continuation projects [web-greeter](https://github.com/JezerM/web-greeter) / [nody-greeter](https://github.com/JezerM/nody-greeter).
