### ISSUE TITLE
[bug] power buttons onclick not working

### ISSUE THREAD

**Issue by mathewjhan** [hertg/lightdm-neon#8]
Hopefully it's not just me, but clicking on any of the power buttons doesn't do anything. 

Not too familiar with svelte, but from my cursory glance at the source and comparing it to examples from documentation, it seems like it should work fine. From debugging the element, it seems like the event listener gets attached, but nothing happens if I click it. 

Running `window.lightdm.shutdown()` and other similar methods from the debug console work fine.

Versions:
  - `web-greeter`: 3.5.1
  - `lightdm`: 1.32.0
  - `lightdm-theme-neon-git`: 1:r74.82fcdb7-1

Let me know if you want other logs as well.

**Comment by Iwaslazkis** [comment]
> Hopefully it's not just me, ...

I can confirm I am also having the same issue on my machine, so I don't think its just you lol. I am running the exact same versions as @mathewjhan.

**Comment by hertg** [comment]
Thanks for reporting the issue. I am able to reproduce with [web-greeter](https://github.com/JezerM/web-greeter), but it seems to work on [nody-greeter](https://github.com/JezerM/nody-greeter) which is curious. I got an idea what might be the culprit though, I will try out an easy fix.

**Comment by hertg** [comment]
@mathewjhan @Iwaslazkis 
I added a new commit that should fix the issue, please update and report back if the problem still persists.

**Comment by Iwaslazkis** [comment]
Sorry for the very late response, but just wanted to let you know that indeed things have been fixed on my end for a little while! I'm assuming I updated it with AUR helper a while ago after you sent that commit, which must've fixed things. Thank you for your help and this wonderful theme! 😄
